✨ Create vote result pages and svg

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -62,3 +62,19 @@ jobs:
         if: github.ref == 'refs/heads/main' && github.repository == ${{ env.REPO }}
         id: deployment
         uses: actions/deploy-pages@v4
+
+  check:
+    runs-on: ubuntu-latest
+    needs: publish
+    if: always()
+    steps:
+      - if: ${{ needs.publish.result != 'failure' }}
+        run: |
+          echo "Deployment successful"
+
+      - if: ${{ needs.publish.result == 'failure' }}
+        run: |
+          echo "Deployment failed"
+          exit 1
+
+
